### ISSUE TITLE
关于 PageTable 组件

### ISSUE THREAD

**Issue by bruningSnow** [LagrangeLabs/ii-admin-business#27]
1、IPageTableProps 缺少相关 style、classname
2、IPageTableProps onTreeSelect 属性为必选
3、整个 IPageTableProps 存在默认边距

**Comment by xueyang996** [comment]
businees 业务组件，更贴近于ui规范，应该推动ui规范改进，不建议传入更多配置项
若需修改，可以全局修改组件样式
